### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mendix/munin-plugins-mendix#10]
Can you please add a license?

**Comment by knorrie** [comment]
Hi Alessandro,

Yes, that is obviously something that needs to happen in here, thanks for asking. Actually, I think we should remove all of this from github instead since it's a bit of an ancient pile of tie wraps and duct tape, cruft included.

But, if you have found something that you can reuse, then let's make that happen first. :-)

I just opened #11 to add it.

Don't hesitate to ask a bit more about what you need.

Hans

**Comment by knorrie** [comment]
Hi! A LICENSE file was added. Have fun!

**Comment by Alessandro-Barbieri** [comment]
Thank you alot
